export const GET_PRODUCT_LOADING = "GET_PRODUCT_LOADING"; 
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"; 
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const GET_PRODUCT_DETAILED_LOADING = "GET_PRODUCT_DETAILED_LOADING"; 
export const GET_PRODUCT_DETAILED_SUCCESS = "GET_PRODUCT_DETAILED_SUCCESS"; 
export const GET_PRODUCT_DETAILED_ERROR = "GET_PRODUCT_DETAILED_ERROR"; 

export const GET_ERROR = "GET_ERROR"; 